/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as notAuthLayoutImport } from './routes/(not-auth)/layout'
import { Route as authLayoutImport } from './routes/(auth)/layout'
import { Route as PageImport } from './routes/page'
import { Route as notAuthLoginPageImport } from './routes/(not-auth)/login/page'
import { Route as authDashboardPageImport } from './routes/(auth)/dashboard/page'
import { Route as authDashboardCardPayCardPageImport } from './routes/(auth)/dashboard/card/pay-card/page'
import { Route as authDashboardCardBenefitsPageImport } from './routes/(auth)/dashboard/card/benefits/page'
import { Route as authDashboardAccountAccountStatusPageImport } from './routes/(auth)/dashboard/account/account-status/page'

// Create/Update Routes

const notAuthLayoutRoute = notAuthLayoutImport.update({
  id: '/(not-auth)',
  getParentRoute: () => rootRoute,
} as any)

const authLayoutRoute = authLayoutImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const PageRoute = PageImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const notAuthLoginPageRoute = notAuthLoginPageImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => notAuthLayoutRoute,
} as any)

const authDashboardPageRoute = authDashboardPageImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => authLayoutRoute,
} as any)

const authDashboardCardPayCardPageRoute =
  authDashboardCardPayCardPageImport.update({
    id: '/dashboard/card/pay-card/',
    path: '/dashboard/card/pay-card/',
    getParentRoute: () => authLayoutRoute,
  } as any)

const authDashboardCardBenefitsPageRoute =
  authDashboardCardBenefitsPageImport.update({
    id: '/dashboard/card/benefits/',
    path: '/dashboard/card/benefits/',
    getParentRoute: () => authLayoutRoute,
  } as any)

const authDashboardAccountAccountStatusPageRoute =
  authDashboardAccountAccountStatusPageImport.update({
    id: '/dashboard/account/account-status/',
    path: '/dashboard/account/account-status/',
    getParentRoute: () => authLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageImport
      parentRoute: typeof rootRoute
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authLayoutImport
      parentRoute: typeof rootRoute
    }
    '/(not-auth)': {
      id: '/(not-auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof notAuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/dashboard/': {
      id: '/(auth)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authDashboardPageImport
      parentRoute: typeof authLayoutImport
    }
    '/(not-auth)/login/': {
      id: '/(not-auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof notAuthLoginPageImport
      parentRoute: typeof notAuthLayoutImport
    }
    '/(auth)/dashboard/account/account-status/': {
      id: '/(auth)/dashboard/account/account-status/'
      path: '/dashboard/account/account-status'
      fullPath: '/dashboard/account/account-status'
      preLoaderRoute: typeof authDashboardAccountAccountStatusPageImport
      parentRoute: typeof authLayoutImport
    }
    '/(auth)/dashboard/card/benefits/': {
      id: '/(auth)/dashboard/card/benefits/'
      path: '/dashboard/card/benefits'
      fullPath: '/dashboard/card/benefits'
      preLoaderRoute: typeof authDashboardCardBenefitsPageImport
      parentRoute: typeof authLayoutImport
    }
    '/(auth)/dashboard/card/pay-card/': {
      id: '/(auth)/dashboard/card/pay-card/'
      path: '/dashboard/card/pay-card'
      fullPath: '/dashboard/card/pay-card'
      preLoaderRoute: typeof authDashboardCardPayCardPageImport
      parentRoute: typeof authLayoutImport
    }
  }
}

// Create and export the route tree

interface authLayoutRouteChildren {
  authDashboardPageRoute: typeof authDashboardPageRoute
  authDashboardAccountAccountStatusPageRoute: typeof authDashboardAccountAccountStatusPageRoute
  authDashboardCardBenefitsPageRoute: typeof authDashboardCardBenefitsPageRoute
  authDashboardCardPayCardPageRoute: typeof authDashboardCardPayCardPageRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authDashboardPageRoute: authDashboardPageRoute,
  authDashboardAccountAccountStatusPageRoute:
    authDashboardAccountAccountStatusPageRoute,
  authDashboardCardBenefitsPageRoute: authDashboardCardBenefitsPageRoute,
  authDashboardCardPayCardPageRoute: authDashboardCardPayCardPageRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface notAuthLayoutRouteChildren {
  notAuthLoginPageRoute: typeof notAuthLoginPageRoute
}

const notAuthLayoutRouteChildren: notAuthLayoutRouteChildren = {
  notAuthLoginPageRoute: notAuthLoginPageRoute,
}

const notAuthLayoutRouteWithChildren = notAuthLayoutRoute._addFileChildren(
  notAuthLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof notAuthLayoutRouteWithChildren
  '/dashboard': typeof authDashboardPageRoute
  '/login': typeof notAuthLoginPageRoute
  '/dashboard/account/account-status': typeof authDashboardAccountAccountStatusPageRoute
  '/dashboard/card/benefits': typeof authDashboardCardBenefitsPageRoute
  '/dashboard/card/pay-card': typeof authDashboardCardPayCardPageRoute
}

export interface FileRoutesByTo {
  '/': typeof notAuthLayoutRouteWithChildren
  '/dashboard': typeof authDashboardPageRoute
  '/login': typeof notAuthLoginPageRoute
  '/dashboard/account/account-status': typeof authDashboardAccountAccountStatusPageRoute
  '/dashboard/card/benefits': typeof authDashboardCardBenefitsPageRoute
  '/dashboard/card/pay-card': typeof authDashboardCardPayCardPageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof PageRoute
  '/(auth)': typeof authLayoutRouteWithChildren
  '/(not-auth)': typeof notAuthLayoutRouteWithChildren
  '/(auth)/dashboard/': typeof authDashboardPageRoute
  '/(not-auth)/login/': typeof notAuthLoginPageRoute
  '/(auth)/dashboard/account/account-status/': typeof authDashboardAccountAccountStatusPageRoute
  '/(auth)/dashboard/card/benefits/': typeof authDashboardCardBenefitsPageRoute
  '/(auth)/dashboard/card/pay-card/': typeof authDashboardCardPayCardPageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/account/account-status'
    | '/dashboard/card/benefits'
    | '/dashboard/card/pay-card'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/account/account-status'
    | '/dashboard/card/benefits'
    | '/dashboard/card/pay-card'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(not-auth)'
    | '/(auth)/dashboard/'
    | '/(not-auth)/login/'
    | '/(auth)/dashboard/account/account-status/'
    | '/(auth)/dashboard/card/benefits/'
    | '/(auth)/dashboard/card/pay-card/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  authLayoutRoute: typeof authLayoutRouteWithChildren
  notAuthLayoutRoute: typeof notAuthLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  authLayoutRoute: authLayoutRouteWithChildren,
  notAuthLayoutRoute: notAuthLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(auth)",
        "/(not-auth)"
      ]
    },
    "/": {
      "filePath": "page.tsx"
    },
    "/(auth)": {
      "filePath": "(auth)/layout.tsx",
      "children": [
        "/(auth)/dashboard/",
        "/(auth)/dashboard/account/account-status/",
        "/(auth)/dashboard/card/benefits/",
        "/(auth)/dashboard/card/pay-card/"
      ]
    },
    "/(not-auth)": {
      "filePath": "(not-auth)/layout.tsx",
      "children": [
        "/(not-auth)/login/"
      ]
    },
    "/(auth)/dashboard/": {
      "filePath": "(auth)/dashboard/page.tsx",
      "parent": "/(auth)"
    },
    "/(not-auth)/login/": {
      "filePath": "(not-auth)/login/page.tsx",
      "parent": "/(not-auth)"
    },
    "/(auth)/dashboard/account/account-status/": {
      "filePath": "(auth)/dashboard/account/account-status/page.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/dashboard/card/benefits/": {
      "filePath": "(auth)/dashboard/card/benefits/page.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/dashboard/card/pay-card/": {
      "filePath": "(auth)/dashboard/card/pay-card/page.tsx",
      "parent": "/(auth)"
    }
  }
}
ROUTE_MANIFEST_END */
